### ISSUE TITLE
Code for the  example image && add upper half plane model

### ISSUE THREAD

**Issue by neozhaoliang** [cduck/hyperbolic#1]
Hi: I'm not sure if you are still maintaining this module. It seems that it has not been update for a few years. But I wonder if you could add the source code for the example image (hyperweave) in readme.md? Also have you any plan to add the code for upper half plane model?

**Comment by cduck** [comment]
Thanks for your interest.  Although I'm not ready to share my code for my hyperbolic weave, the tiling examples show how to construct something similar.  The only difference is that each tile draws a portion of a ribbon instead of a regular polygon.

I still maintain this and I have been meaning to add other hyperbolic projections.  Your comment prompted me to add the half-plane model today which is now in version 1.2.0 (see the example notebooks for how to use it).

**Comment by neozhaoliang** [comment]
I'm developing a math project which contains some code for drawing hyperbolic artworks: https://github.com/neozhaoliang/pywonderland
You can see some images here:  http://pywonderland.com/uniform-tilings/
However the approach of generating the tiles is different from yours.
I was thinking this package is obsolete and was going to write a custom one. Glad you updated it, I'll try.

**Comment by neozhaoliang** [comment]
It seems that the "transform" class does not apply to text?

**Comment by cduck** [comment]
`Text` is part of `drawSvg`, not `hyperbolic` so you need to apply the transform manually to it's position by using `*trans.applyToTuple(pt)` in place of `*pt`.

```python
# Half-plane version of one of the examples

#trans = Transform.merge(Transform.diskToHalf(), Transform.translation((-0.00001,0)))  # Upper half plane
trans = Transform.merge(Transform(1j, 1, 1, 1j), Transform.translation((-0.00001,0)))  # Lower half-plane

p1 = Point(0,-.5)
p2 = Point(.5, .5)
hl = Line.fromPoints(*p1, *p2, segment=False)

transMirror = Transform.mirror(p1, p2)
spacing = np.linspace(0.1, 0.9, 5)
pts = [
    *(Point(0,x) for x in spacing),
    *(Point(x,0) for x in spacing),
    *(Point(0,-x) for x in spacing),
    *(Point(-x,0) for x in spacing),
]
ptsMirror = transMirror.applyToList(pts)

d = Drawing(4, 2, origin=(-2, -2))
d.append(draw.Rectangle(-10, -10, 20, 20, fill='#ddd'))

d.draw(hl, hwidth=0.2, transform=trans, fill='white')
d.draw(p1, hradius=0.1, transform=trans, fill='green')
d.draw(p2, hradius=0.1, transform=trans, fill='green')

for i, pt in enumerate(pts):
    d.draw(pt, hradius=0.1, transform=trans, fill='#eee')
    d.append(draw.Text(str(i), 0.05, *trans.applyToTuple(pt), center=0.7))
for i, pt in enumerate(ptsMirror):
    d.draw(pt, hradius=0.1, transform=trans, fill='#eee')
    d.append(draw.Text(str(i), 0.05, *trans.applyToTuple(pt), center=0.7))

d.setRenderSize(w=800)
d
```
![index](https://user-images.githubusercontent.com/2476062/82735702-14f8a380-9d13-11ea-8bb0-e494e4aafa11.png)

**Comment by neozhaoliang** [comment]
![uhp-4-3-3](https://user-images.githubusercontent.com/23307174/82744575-12e32300-9dad-11ea-8766-39fae2502ba5.png)

Thanks, it works fine for me now.

Do you have any plane of implementing the "ring" projection model?

**Comment by cduck** [comment]
Currently only projections that preserve circles are supported (by changing or subclassing `Transform`).  To support other models, it would need to compute all points along the hyperbolic geometry and generate `drawSvg.Path`s for each.  I don't currently have plans to add this myself but contributions are welcome and I don't think this is too hard to implement if you already understand the math.
