### ISSUE TITLE
Polygon.fromVertices chooses wrong orientation for ideal edges

### ISSUE THREAD

**Issue by smh0109** [cduck/hyperbolic#19]
I'm working a lot with ideal triangles right now and it bugs me, that for an edge with  an ideal start- and endpoint the wrong orientation of the line is choosen.
This should demonstrate the problem well enough:
```
import drawSvg as draw
from hyperbolic.poincare.shapes import *

d = draw.Drawing(2.1, 2.1, origin='center')
d.setRenderSize(500)
d.append(draw.Circle(0, 0, 1, fill='silver'))

p1=Point.fromEuclid(-0.104, 0.069)
p2=Point.fromEuclid(-0.182, 0.212)
p3=Point.fromEuclid(-0.622, -0.316)


PList=[p1,p2,p3]
PList=[Ideal(p.theta) for p in PList]

poly=Polygon.fromVertices(PList)

d.draw(poly,stroke='black', stroke_width=0.01, fill='green')
d.draw(Polygon.fromEdges(poly.edges),stroke='red', stroke_width=0.01, fill='white', fill_opacity=0.5)

d
```

**Comment by cduck** [comment]
Thanks for the complete example.  It looks like it is switching the direction of *every* line that is created with two ideal endpoints.  Is that what you see?

It looks like [this line is the bug](https://github.com/cduck/hyperbolic/blob/d5ac6a9cb0d900a96d3a2499da1bc83257469ef4/hyperbolic/poincare/Line.py#L36).  By changing `>` to `<=` (and on line 40) your example works.  Does this fix it for all your use cases?

**Comment by smh0109** [comment]
I agree on what you found and I guess your fix should work for all my use cases.
Thanks for your fast response!
