### ISSUE TITLE
'Transform' has no attribute 'diskToHalf'; Acknowledgement in Publications

### ISSUE THREAD

**Issue by stimhyde** [cduck/hyperbolic#2]
Hi. Thanks for your useful code. I am using it for some fairly simple Poincare disk images for publication and would lkike to acknowledge you - can you tell me what address/handle etc you prefer? 

I am unable to use your HalfPlane model as I get the error

AttributeError: type object 'Transform' has no attribute 'diskToHalf'

(I am a very inexperienced python hacker, so am clearly missing something...)

**Comment by cduck** [comment]
You probably just have an old version installed.  1.3.0 is required for the half plane model.  Check your installed version with `python3 -m pip show hyperbolic` and update to the latest with `python3 -m pip install --upgrade hyperbolic`.

---

Thanks for the positive feedback.  I don't have a software publication you can reference but if you want to cite it you can do something like this (https://academia.stackexchange.com/a/14015):
```
@misc{Duckering2020,
  author = {Duckering, Casey},
  title = {Hyperbolic: A Python 3 library for constructing and drawing hyperbolic geometry},
  year = {2020},
  publisher = {GitHub},
  journal = {GitHub repository},
  howpublished = {\url{https://github.com/cduck/hyperbolic}},
  commit = {6e5937848dc39cfcc9fb629e07fa2c03fd2dbde0}
}
```
(Change the commit to the version you used.  This is for version 1.3.0.)

Or just acknowledge the project by name and URL e.g. "The Hyperbolic Python library (https://github.com/cduck/hyperbolic)" or "The Python library Hyperbolic by Casey Duckering (https://github.com/cduck/hyperbolic)".

For publishing vector diagrams like these, I recommend the `svg` LaTeX package if you aren't already using it.  You can reach me through the email on my [website](https://caseyduckering.com/) if you have questions not directly related to using this library.

**Comment by cduck** [comment]
You can now cite Hyperbolic 1.3.0 as:
```
@software{casey_duckering_2020_3978772,
  author       = {Casey Duckering},
  title        = {cduck/hyperbolic: Hyperbolic 1.3.0},
  month        = aug,
  year         = 2020,
  publisher    = {Zenodo},
  version      = {1.3.0},
  doi          = {10.5281/zenodo.3978772},
  url          = {https://doi.org/10.5281/zenodo.3978772}
}
```
(See the [README](https://github.com/cduck/hyperbolic) for the latest DOI to cite.)

**Comment by stimhyde** [comment]
Thanks for your help. And for your software!
