### ISSUE TITLE
Isn't the point in Poincare model in visualisation inverted?

### ISSUE THREAD

**Issue by Rowing0914** [cduck/hyperbolic#28]
Thank you for publishing your work!

## Background
I'm new to hyperbolic geometry and started playing with this repo recently. I was working on the example code in https://github.com/cduck/hyperbolic/blob/master/examples/poincare.ipynb.

## Issue / Question
Following is the code I used to plot the image below. I am feeling like the yellow point (Cartesian coordinate `(0.0, 0.2)` ) in this Poincare model in visualisation is supposed to be above the origin (a blue point)? Is this inverted in y-axis for some reason?

## Output plot

![image](https://github.com/cduck/hyperbolic/assets/20626792/dc619bf0-40af-4f00-b790-f4a42d6d1989)

## Code

```python
import math
import random

import drawsvg as draw
from drawsvg import Drawing
from hyperbolic import euclid, util
from hyperbolic.poincare import *

d = Drawing(2.1, 2.1, origin='center')
d.draw(euclid.Circle(0, 0, 1), fill='silver')

line_style = dict(hwidth=0.05, fill='black')
d.draw(Point(.0, .2), radius=0.02, fill='orange')
d.draw(Point(.0, .0), radius=0.02, fill='blue')
d.set_render_size(w=400)
d
```

**Comment by cduck** [comment]
Thank you for the complements!

The y-direction going down is expected behavior which changed when I updated to drawsvg 2.  If you want to restore the old y-direction up behavior, use the following:
```python
d = draw.Drawing(2.1, 2.1, origin='center', context=draw.Context(invert_y=True))
```
(From https://github.com/cduck/drawsvg?tab=readme-ov-file#interactive-widget)

**Comment by Rowing0914** [comment]
Got it! Thank you for your response!
