### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by VascoSch92** [cduck/hyperbolic#29]
Is this repository still maintained?

**Comment by cduck** [comment]
Yes.

**Comment by cduck** [comment]
To clarify, I still maintain this package but for PRs adding new features, I have not had time in the past year to test their code myself.  I appreciate your code reviews and pinging me about this.

**Comment by VascoSch92** [comment]
I 'm interested in the package. I wanted to do something similar myself but you already did great ,-)

You don't have tests. If you want I could add tests to make your life easier. In this way if there is a PR you can see if the test are passing or not.

what do you think?

**Comment by cduck** [comment]
Thank you for the offer.  I would be grateful if you add continuous integration tests or even auto-formatting.

**Comment by VascoSch92** [comment]
Yes I could do that. ;-)

Let's start with tests and then we can speak about auto-formatting
