### ISSUE TITLE
tilling isosceles triangles

### ISSUE THREAD

**Issue by SkyFishMoon** [cduck/hyperbolic#5]
Hello, could you please share an example of code about how to draw the second picture in README that tiling the poincare disk with isosceles triangles ?

**Comment by cduck** [comment]
Sure.  I added a new [example notebook](https://github.com/cduck/hyperbolic/blob/master/examples/isosceles-tiling.ipynb).  It's based on splitting each 7-sided polygon of a regular tiling into 7 isosceles triangles.

**Comment by SkyFishMoon** [comment]
thanks very much
